language: python
env:
  global:
    - TEST_REQUIREMENTS=social/tests/requirements.txt
python:
  - "2.6"
  - "2.7"
  - "pypy"
matrix:
  include:
    - python: "3.3"
      env: TEST_REQUIREMENTS=social/tests/requirements-python3.txt
    - python: "3.4"
      env: TEST_REQUIREMENTS=social/tests/requirements-python3.txt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxmlsec1-dev swig
install:
  - "python setup.py -q install"
  - "travis_retry pip install -r $TEST_REQUIREMENTS"
script:
  - "nosetests --with-coverage --cover-package=social --where=social/tests"
